version: "3.8"

services:
  mysql_db:
    container_name: mysql_db
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker_db
    ports:
      - 3307:3307
    volumes:
      - db:/var/lib/mysql
  ui:
    depends_on:
      - square
      - cube
      - fibonacci
      - metrics
    container_name: ui-service
    build: ./serviceUI
    restart: on-failure
    ports:
      - 7070:7070
  square:
    depends_on:
      - mysql_db
    container_name: square-service
    build: ./serviceSquare
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql_db:3307/docker_db?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  cube:
    depends_on:
      - mysql_db
    container_name: cube-service
    build: ./serviceCube
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql_db:3307/docker_db?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  fibonacci:
    depends_on:
      - mysql_db
    container_name: fibonacci-service
    build: ./serviceFibonacci
    restart: on-failure
    ports:
      - 8083:8083
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql_db:3307/docker_db?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  metrics:
    depends_on:
      - mysql_db
    container_name: metrics-service
    build: ./serviceMetrics
    restart: on-failure
    ports:
      - 8084:8084
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql_db:3307/docker_db?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
