version: "3.8"

services:
  mysql_db:
    container_name: mysql_db
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  ui:
    container_name: ui-service
    build: ./serviceUI
    restart: on-failure
    ports:
      - 7070:7070
    depends_on:
      - square
      - cube
      - fibonacci
      - metrics
  square:
    container_name: square-service
    build: ./serviceSquare
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/docker_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql_db
  cube:
    container_name: cube-service
    build: ./serviceCube
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/docker_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql_db
  fibonacci:
    container_name: fibonacci-service
    build: ./serviceFibonacci
    restart: on-failure
    ports:
      - 8083:8083
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/docker_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql_db
  metrics:
    container_name: metrics-service
    build: ./serviceMetrics
    restart: on-failure
    ports:
      - 8084:8084
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/docker_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql_db
volumes:
  db:
